### PR TITLE
Bundler clean task

### PR DESCRIPTION
**Pull request by will-in-wi**
Followup to comments on https://github.com/capistrano/bundler/pull/68

Per @betesh's comment:
> feel free to open another PR if there's followup after @mattbrictson gives feedback

### CODE REVIEW

**Comment by mattbrictson** [comment]
LGTM. @will-in-wi you've tested this in an actual deployment, right? Since this project lacks tests I will need to take your word for it. 😄

**Comment by will-in-wi** [comment]
I just tested this. It worked fine.

**Comment by mattbrictson** [comment]
Great, thanks for taking care of this!

**Comment by mattbrictson** [comment]
This will be released as capistrano-bundler 1.2.0 as soon as I get rubygems access. 😃

**Pull request merged**
